### ISSUE TITLE
Consider Renaming Environment class

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [kwaclaw/KdSoft.Lmdb#1]
Hello, thanks for this great library.

The class `Environment` conflicts with `System.Environment` right away when you use the library. I have to alias `Environment` to use it.

Have you considered renaming it to something else like `LmdbEnvironment` or something?

**Comment by kwaclaw** [comment]
Good question, I struggle sometimes with this, because obviously, we have
namespaces for that purpose, so in theory we should not have to avoid
naming conflicts as long as we have a unique namespace. However, certain
namespaces (like System) are almost always in the file header's usings, so
in this case we would need to use "using lmdb = KdSoft.Lmdb;"  to have an
alias.

I am not sure yet which way I am leaning, but If I change it I need to
change all other names that look like EnvironmentXXX , in order to be
consistent.

**Comment by AlgorithmsAreCool** [comment]
Yes this wouldn't be an issue except that System is almost always in scope so the conflict is very hard to avoid.

**Comment by kwaclaw** [comment]
OK, I will rename it. Will require a major version increment to 2.0.0.
